# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  NUM_FIXES: '3'

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  simulate-alpha-fixes:
    desc: Simulate fix commits for alpha branch
    vars:
      FIXES: '{{.NUM_FIXES | default "3"}}'
    cmds:
      - echo "Simulating {{.FIXES}} fix commits for alpha..."
      - |
        for i in $(seq 1 {{.FIXES}}); do
          echo "A fix" >> README.md
          git add README.md
          git commit -m "fix: apply fix number $i"
          echo "✅ Created fix commit $i"
        done
      - echo "✨ Done! Created {{.FIXES}} fix commits."
      - echo "💡 Push to alpha branch: git push origin alpha"

  simulate-feat-fix:
    desc: Simulate feature then fix commits for alpha branch
    cmds:
      - echo "Simulating feature commit..."
      - echo "A feature" >> README.md
      - git add README.md
      - git commit -m "feat: add new feature"
      - echo "✅ Created feature commit"
      - echo "Simulating fix commit..."
      - echo "A fix" >> README.md
      - git add README.md
      - git commit -m "fix: apply fix after feature"
      - echo "✅ Created fix commit"
      - echo "✨ Done! Created 1 feature + 1 fix commits."
      - echo "💡 Push to alpha branch: git push origin alpha"

  simulate-fix-feat:
    desc: Simulate fix then feature commits for alpha branch
    cmds:
      - echo "Simulating fix commit..."
      - echo "A fix" >> README.md
      - git add README.md
      - git commit -m "fix: apply fix first"
      - echo "✅ Created fix commit"
      - echo "Simulating feature commit..."
      - echo "A feature" >> README.md
      - git add README.md
      - git commit -m "feat: add new feature"
      - echo "✅ Created feature commit"
      - echo "✨ Done! Created 1 fix + 1 feature commits."
      - echo "💡 Push to alpha branch: git push origin alpha"
